spring.application.name=flex

# DATABASE (Render will inject values)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# FILE STORAGE (IMPORTANT FIX)
file.upload-dir=uploads/

# JWT
jwt.secret=MySuperSecureJwtSecretKey1234567890

# EMAIL (better to move to env later)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chiragchangappa02@gmail.com
spring.mail.password=zrzouirtyuitoeal
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RAZORPAY (better to move to env later)
razorpay.key.id=rzp_live_SiBeiJTB5u1A3k
razorpay.key.secret=ZuctMMSpxSs1jPzTqbYp7ql8