spring.application.name=flex
spring.datasource.url=jdbc:postgresql://localhost:5432/flexdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.upload-dir=c:/flex-uploads/

jwt.secret=MySuperSecureJwtSecretKey1234567890
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chiragchangappa02@gmail.com
spring.mail.password=zrzouirtyuitoeal
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
razorpay.key.id=rzp_live_SiBeiJTB5u1A3k
razorpay.key.secret=ZuctMMSpxSs1jPzTqbYp7ql8