spring.application.name=flex

# DATABASE (LOCAL POSTGRES OR MYSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/flexdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# FILE STORAGE
file.upload-dir=uploads/

# JWT
jwt.secret=MySuperSecureJwtSecretKey1234567890

# EMAIL (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chiragchangappa02@gmail.com
spring.mail.password=zrzouirtyuitoeal
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RAZORPAY (TEST MODE recommended for localhost)
razorpay.key.id=rzp_test_xxxxxxxx
razorpay.key.secret=xxxxxxxxxxxx

server.port=${PORT:8080}